formations:
  db:
    description: "mysql rds instance"
    rds:
      db01:
        tags:
          environment_tags:
            prod:
              Role: "Rds Instance"
            preprod:
              Role: "Rds Instance"
        db:
          allocated_storage: "50"
          auto_minor_version_upgrade: true
          instance_class: "db.m3.large"
          engine_version: "5.5.33"
          family: "mysql5.5"
          multiaz: true
          master_username: "root"
          app_username: "appname"
        extra_dns: "mysql"
        dns:
          MyDBDnsRecord:
            name: "rds"
            resource: "db01"
            resource_type: "Endpoint.Address"
            type: "CNAME"
        ec2_security_group:
          group_description: "rds security group"
          from_port: "3306"
          to_port: "3306"
        rds_subnet_group:
          group_description: "rds subnet group"
db_parameters:
   character_set_client: "utf8"
   character_set_connection: "utf8"
   character_set_database: "utf8"
   character_set_filesystem: "Binary"
   character_set_results: "utf8"
   character_set_server: "utf8"
   collation_connection: "utf8_bin"
   collation_server: "utf8_bin"