wp:
  bucket:
    principals:
    - "arn:aws:iam::12231312xxxx:user/larssonp"
    - "arn:aws:iam::12231312xxxx:role/instance_role"
  cw-cf-templates:
    principals:
    - "arn:aws:iam::537625697240:user/martin.crowell"
    - "arn:aws:iam::537625697240:user/pierrel"
  cw-secure:
    principals:
    - "arn:aws:iam::537625697240:user/martin.crowell"
    - "arn:aws:iam::537625697240:user/pierrel"