security_groups:
  wp:
    base:
      ssh:
        cidr:
        - 195.35.90.111/32
        config:
          description: world 22 incoming
          from_port: '22'
          protocol: tcp
          to_port: '22'
  env:
    nat:
      preprod-network:
        cidr:
        - 10.0.0.0/8
        config:
          description: "all preprod networks"
          from_port: '0'
          protocol: '-1'
          to_port: '0'
    base:
      atlassian-network:
        cidr:
        - 165.254.226.0/23
        - 131.103.26.0/23
        - 131.103.29.0/24
        config:
          description: atlassian network
          from_port: '80'
          protocol: tcp
          to_port: '80'
    akamai:
      http:
        cidr:
        - 122.160.242.0/24
        - 124.40.42.0/24
        - 125.56.205.0/24
        - 144.135.8.0/24
        - 184.26.162.0/24
        - 184.51.198.0/24
        - 195.59.44.0/24
        - 204.2.166.0/24
        - 205.160.30.0/24
        - 209.170.118.0/24
        - 216.246.75.0/24
        - 217.212.225.0/24
        - 23.63.227.0/24
        - 23.67.252.0/24
        - 46.33.69.0/24
        - 59.144.112.0/24
        - 60.254.142.0/24
        - 60.254.148.0/24
        - 63.141.200.0/24
        - 72.246.64.0/24
        - 72.246.65.0/24
        - 77.67.126.0/24
        - 80.239.228.0/24
        - 81.52.140.0/24
        - 96.17.182.0/24
        config:
          description: "akamai http"
          from_port: '80'
          protocol: tcp
          to_port: '80'